name: release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@main
        with:
          java-version: 17
          maven-version: 3.9.8

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "4.3.1"
          name: "Eureka Server 4.3.1"
          draft: false
          prerelease: false

      - name: Upload firmware with custom name
        uses: softprops/action-gh-release@v1
        with:
          files: target/eureka-server.jar
          tag_name: "4.3.1"
